before_install:
  - gem uninstall bundler -aIxq --force
  - gem uninstall -Ixq --force -i /home/travis/.rvm/gems/ruby-2.2.3@global bundler
  - gem install bundler -v '1.12.5'

rvm:
  - 2.2.3

gemfile: Gemfile

sudo: false
